# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
      - id: black

  - repo: https://gitlab.com/PyCQA/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
